services:
  well-versed-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:7860"
    networks:
      - monitoring
  prometheus:
    depends_on:
      - well-versed-ai-app
    build:
      context: ./Prometheus
      dockerfile: Dockerfile
    ports:
      - "3334:9090"
    networks:
      - monitoring
  grafana:
    depends_on:
      - prometheus
    build:
      context: ./Grafana
      dockerfile: Dockerfile
    ports:
      - "3335:3000"
    networks:
      - monitoring

networks:
  monitoring: 
    external: true
    name: monitoring